language: node_js
node_js:
- '6'

branches:
  only:
    - development

cache:
  directories:
  - node_modules

tex-config:
  tex-scheme=small
  push-type=none
  build-pattern=*.tex
  packages=lipsum, abc

before_install:
  - cd ./travis/
  - ./installbookdeps.sh
  - WD="$(pwd)";
  - export PATH="$PATH:$WD/download/ps2eps/bin:$WD/download/abcm2ps:$WD/download/epstopdf"
  - cd ..

script:
  - node generate.js
  - node generate.js --books
  - npm test;

after_success:
  - cd ./travis/
  - ./deploy.sh
  - cd ..
