name: Build Tunebook

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the tunebook

    steps:
      - name: Check out tunebook
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: npm Caching
        # We use node js packages stored in this repository keeping them
        # reliable.
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: install dependencies
        # Build depends on three conversion scripts provided externally.
        run: |
          sudo apt install abcm2ps
          abcm2ps -V
          sudo apt install ps2eps
          ps2eps -V
          curl -L http://mirrors.ctan.org/support/epstopdf.zip -o ./epstopdf.zip
          unzip ./epstopdf.zip
          mv ./epstopdf/epstopdf.pl ./epstopdf/epstopdf
          chmod a+x ./epstopdf/epstopdf
          ./epstopdf/epstopdf -V
          npm install

      - name: create tunebook
        run: |
          node generate.js index
          node generate.js books
          npm test;

      - name: Upload built website
        uses: actions/upload-artifact@v3
        with:
          name: tune-index
          path: tunes.json

  # This script sets up git for the deployment and commits the changes
  # to the branch "master".
  
          # git remote add origin-pages https://git@github.com/wxtim/bristolfolksoc.github.io.git > /dev/null 2>&1
          # git push --quiet -f origin-pages master
  deploy:
    if: github.branch == 'Change-to-Github-Actions-test'
    runs-on: ubuntu-latest
    name: Deploy the tunebook
    needs: build

    steps:
      - name: Check out tunebook
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install production dependencies
        run: /
          npm install --production
        
      - name: Download math result for job 2
        uses: actions/download-artifact@v3
        with:
          name: homework

      - name: deploy tunebook
        run: |
          git add -f *.pdf
          git add -f node_modules
          git add -f tunes.json
          git commit -m "Build"
          git config --global user.email "deploy@travis-ci.org"
          git config --global user.name "Deployment Bot"
          git remote -v
